# Generated by Django 4.2.7 on 2026-06-07 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_email_column_size'),
        ('core', '0044_create_notificaciones_tables'),
    ]

    operations = [
    ]
